FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
# Asegúrate de instalar todas las dependencias, incluidas las de desarrollo para la fase de build
RUN npm install --production=false

COPY . .

# Ejecuta el script de build de tu package.json ("tsc && vite build")
RUN npm run build

# El CMD ya es correcto para el backend compilado
CMD ["node", "dist-backend/index.js"]
EXPOSE 3001
