FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Compila el código TypeScript a JavaScript
RUN npx tsc --project tsconfig.server.json

# Ejecuta el código compilado
CMD ["node", "dist-backend/index.js"]
EXPOSE 3001